#include ../../common.mk
#	go get -v github.com/hajimehoshi/ebiten
ACOUNT_NAME=CHANGETEXTHERE
run:
	go mod init github.com/${ACOUNT_NAME}/${ACOUNT_NAME}
	go get -v github.com/hajimehoshi/ebiten
	go run main.go 33
